# Generated by Django 4.0.1 on 2022-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('text', models.TextField(verbose_name='Описание нас')),
                ('image', models.ImageField(upload_to='about_image')),
            ],
            options={
                'verbose_name': 'Про меня',
                'verbose_name_plural': 'Про нас',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блога')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг для блога')),
                ('description', models.TextField(verbose_name='Текст для блога')),
                ('blog_image', models.ImageField(upload_to='blog_image/', verbose_name='Изображение для блога')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Время публикации')),
                ('draft', models.BooleanField(default=True, verbose_name='Чероновик')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=5000, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название для поля фотографий ')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг для поля фото')),
                ('text', models.TextField(verbose_name='Описание для фотографий')),
                ('photo_image', models.ImageField(upload_to='photo_image/', verbose_name='Изображение для фото коллекции')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('draft', models.BooleanField(default=True, verbose_name='Чероновик')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-date'],
            },
        ),
    ]
